name: uni_links
description: Flutter plugin for accepting incoming links - App/Deep Links (Android), Universal Links and Custom URL schemes (iOS).
version: 0.4.0
homepage: https://github.com/avioli/uni_links

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: name.avioli.unilinks
        pluginClass: UniLinksPlugin
      ios:
        pluginClass: UniLinksPlugin

